# Generated by Django 3.2.8 on 2021-10-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='isDone',
            field=models.BooleanField(default=False),
        ),
    ]
