# Generated by Django 3.2.8 on 2021-10-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_requests_isdone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
